#!/bin/bash

LVL_PATH=$HOME/uploads/lvlfiles
CFG_PATH=$HOME/uploads/configs
ZONE_ARENAS_PATH=$HOME/zone/arenas

#lvlfiles=$(find $HOME/uploads/lvlfiles -name "*.lvl" -type f -printf "%f ")
num_lvlfiles=0
num_cfgfiles=0
for lvlfile in $LVL_PATH/*.lvl; do
    num_lvlfiles=$(expr $num_lvlfiles + 1)
    arena=${lvlfile##*/}
    arena=${arena%.lvl}
    lvlfile=${LVL_PATH}/${arena}.lvl
    lvlcfg=${CFG_PATH}/${arena}.cfg
    mkdir ${ZONE_ARENAS_PATH}/${arena}
    cp $lvlfile ${ZONE_ARENAS_PATH}/${arena}
    if [ -e  $lvlcfg ]; then
        cp $lvlcfg ${ZONE_ARENAS_PATH}/${arena}
	echo "#include conf/svs/svs.conf
#include ${arena}.cfg

[ General ]
Map=${arena}.lvl" > ${ZONE_ARENAS_PATH}/${arena}/arena.conf
    else
	echo "#include conf/svs/svs.conf

[ General ]
Map=${arena}.lvl" > ${ZONE_ARENAS_PATH}/${arena}/arena.conf
    fi
done

echo "num_lvlfiles="$num_lvlfiles
echo "num_cfgfiles="$num_cfgfiles
